User chyba branch
TheKTM1/Plantasia pull request #14
Opened 2023-05-22 20:01 UTC by Kripsu

No to wrzuciłem usera, w Program.cs póki co wykomentowane bo nie wiem jak to działa, żeby user był zapamiętany przez program, a nie tak, że za każdym wyłączeniem programu trzeba go rejestrować od nowa

2023-05-27 09:40 UTC, shipurjan commented on Plantasia/Models/User.cs
> +﻿namespace Plantasia.Models
zły encoding

2023-05-27 09:40 UTC, shipurjan commented on Plantasia/Program.cs
> +LastName = "W�sacz",
zły encoding

2023-05-27 09:44 UTC, shipurjan requested changes
Masz źle ustawionego gita, bo commituje pliki w złym encodingu (polskie znaczki przekształca w dziwne symbole)
![image](https://github.com/TheKTM1/Plantasia/assets/57770826/7c2ea3ab-382f-41d7-ab49-e9e03c3bccc9)

A druga sprawa to raczej nie commituje się zakomentowanego kodu, tylko coś działającego, bo pewnie nikt tego już nie  odkomentuje

Nie wiem co masz z tym encodingiem ale to wina albo gita albo edytora tekstu. Jak edytowałeś w Visualu to powinno być dobrze, więc raczej kwestia gita. Najszybciej chyba byłoby odinstalować i zainstalować na nowo stąd https://git-scm.com/download/win bo tam w domyślnych ustawieniach jest ustawiony encoding


Albo usuń zakomentowany kod albo go odkomentuj i napraw polskie znaczki

2023-05-29 12:59 UTC, Kripsu commented
Dobra, postaram się to ogarnąć, dzięki za feedback

sob., 27 maj 2023 o 11:44 Cyprian Zdebski ***@***.***>
napisał(a):

> ***@***.**** requested changes on this pull request.
>
> Masz źle ustawionego gita, bo commituje pliki w złym encodingu
> [image: image]
> <https://user-images.githubusercontent.com/57770826/241376877-22a268f6-6d4f-40c6-81b1-c24a3d9fcbeb.png>
> [image: image]
> <https://user-images.githubusercontent.com/57770826/241376885-7c2ea3ab-382f-41d7-ab49-e9e03c3bccc9.png>
>
> A druga sprawa to raczej nie commituje się zakomentowanego kodu, tylko coś
> działającego, bo pewnie nikt tego nie odkomentuje
>
> Nie wiem co masz z tym encodingiem ale to wina albo gita albo edytora
> tekstu. Jak edytowałeś w Visualu to powinno być dobrze, więc raczej kwestia
> gita. Najszybciej chyba byłoby odinstalować i zainstalować na nowo stąd
> https://git-scm.com/download/win bo tam w domyślnych ustawieniach jest
> ustawiony encoding
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TheKTM1/Plantasia/pull/14#pullrequestreview-1447286265>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV7TBPL5BA23NT4ASV2PDZ3XIHEHVANCNFSM6AAAAAAYK4WPX4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-29 13:00 UTC, Kripsu commented
A zostawiłem zakomentowane, bo robiłem to na zasadzie tak jak użytkownicy
są w tym u Fałata i Konrad mi z tym pomagał :p i sprawa też była taka, że
jak mamy to u Fałata zrobione to Ci użytkownicy się zapisywali, a u nas się
nie zapisywali, no i oboje nie wiedzieliśmy czemu, no to zostawiłem to w
takiej formie, ale no to od komentuje to po prostu

pon., 29 maj 2023 o 14:59 Kripsu ***@***.***> napisał(a):

> Dobra, postaram się to ogarnąć, dzięki za feedback
>
> sob., 27 maj 2023 o 11:44 Cyprian Zdebski ***@***.***>
> napisał(a):
>
>> ***@***.**** requested changes on this pull request.
>>
>> Masz źle ustawionego gita, bo commituje pliki w złym encodingu
>> [image: image]
>> <https://user-images.githubusercontent.com/57770826/241376877-22a268f6-6d4f-40c6-81b1-c24a3d9fcbeb.png>
>> [image: image]
>> <https://user-images.githubusercontent.com/57770826/241376885-7c2ea3ab-382f-41d7-ab49-e9e03c3bccc9.png>
>>
>> A druga sprawa to raczej nie commituje się zakomentowanego kodu, tylko
>> coś działającego, bo pewnie nikt tego nie odkomentuje
>>
>> Nie wiem co masz z tym encodingiem ale to wina albo gita albo edytora
>> tekstu. Jak edytowałeś w Visualu to powinno być dobrze, więc raczej kwestia
>> gita. Najszybciej chyba byłoby odinstalować i zainstalować na nowo stąd
>> https://git-scm.com/download/win bo tam w domyślnych ustawieniach jest
>> ustawiony encoding
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/TheKTM1/Plantasia/pull/14#pullrequestreview-1447286265>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AV7TBPL5BA23NT4ASV2PDZ3XIHEHVANCNFSM6AAAAAAYK4WPX4>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-05-29 23:08 UTC, Kripsu commented
Zrobiłem te same zmiany co w Abstract Classes, tam Github mówi, że git i puścił to, tutaj mi krzyczy, że build failed (: Nie mam pojęcia o co chodzi ale no i tak Pushnąłem, zrequestowane przez Cypriana zmiany wprowadzone

2023-05-30 14:10 UTC, shipurjan commented
@YamanoK @TheKTM1 Sprawdźcie

2023-06-18 13:08 UTC, merged